# Generated by Django 4.1.3 on 2022-11-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shortenedurl",
            name="slug",
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
    ]
