# Generated by Django 4.1.3 on 2022-11-30 13:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_shortenedurl_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="shortenedurl",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shortenedurl",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
